### ISSUE TITLE
Convert Slack links in to Linen Links

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#565]
When someone syncs Slack conversations into Linen it is useful to have the links be converted in to Linen URLs. Slack has a 90 day retention so if someone clicks on a link to Slack archive often times it disappears

**Comment by erinkcochran87** [comment]
Bump on this! This would be super, super helpful to have.

**Comment by emilos** [comment]
hey @erinkcochran87, thanks for checking. I think that @cheeseblubber was just cleaning up issues and marked this as done by accident. We definitely want to build this out :).

**Comment by erinkcochran87** [comment]
Oh gosh, that's absolutely excellent! Thank you so much! <3

**Comment by emilos** [comment]
hey @erinkcochran87, it took us a while to get to it, but I just merged the first version [here](https://github.com/Linen-dev/linen.dev/commit/bf32a40e445759c4d144d508bffa06fed14715ba). I've been testing this out in few communities and seems to work OK, but linking is tricky so I would highly appreciate if you could test it out on your end too.

For now, when you click, we'll try to detect if the thread is on our end already, and if it is, you're going to stay within linen vs going to a archived link, which can be empty due to the 90 day limit.

Replacing the link is probably the long term way to go, but it's tricky for subdomains as subdomains can change in the future. We'll try to figure out best approach, at least for now old content will not get lost and will be linkable.

Thanks!

**Comment by erinkcochran87** [comment]
@emilos Wow, thanks so much! Just let my teammate (who implemented this for us) know about this. She'll be OOO for the next few weeks, but I'll try to give it a spin in the mean time. Thanks again for the response 🔥

**Comment by emilos** [comment]
@erinkcochran87 thanks! looking forward to the feedback :) I'll close the issue for now then just to keep things clean.
