### ISSUE TITLE
Doesn't import messages from Discord. 

### ISSUE THREAD

**Issue by glasgowm148** [Linen-dev/linen.dev#572]
Keep turning them on and reconnecting Discord. Only for Linen to not sync anything and toggle them back off. 

Managed to sync three channels by doing it one by one, reconnecting each time; but not working for anymore. 

https://www.linen.dev/d/ergo

**Comment by sandrodesouza** [comment]
Hi Mark, I saw that to join your community there is a verification process that probably assign a new role to the user. Could you give that role to Linen Bot and try to sync again?

**Comment by glasgowm148** [comment]
Thanks! Seems to be working now. Weird it was able to pull in anything that being the issue.

**Comment by glasgowm148** [comment]
Pulled in ~2000 comments and then stopped. Tried reconnecting and will leave it for a bit as it's now displaying 'In Progress' again. It has matching permissions with other bots that work on the specified channels so shouldn't be a permissions issue.

**Comment by cheeseblubber** [comment]
The sync seems like it finished now. We were running in to some performance issues because of an influx of people syncing with Linen. Our syncing background job was getting stuck on some really long running jobs. We scaled up the number of instances for background job service and it looks like all of the syncs that were queued up has been resolved. I'm going to close this for now. Feel free to reopen again if this is still not synced

I'm going to add additional instructions specified in https://github.com/Linen-dev/linen.dev/issues/585 to make sure the Discord bot permissioning doesn't happen again
