### ISSUE TITLE
Suggestion: embed the thread as a comment section on the website.

### ISSUE THREAD

**Issue by meotimdihia** [Linen-dev/linen.dev#728]
The comment is one of the hardest features to build.
And if we can embed them as comment sections like Facebook comments then I think it is great.
https://developers.facebook.com/docs/plugins/comments/

**Comment by cheeseblubber** [comment]
Hey @meotimdihia are you looking to add this to your website? I haven't looked too much in to comment section tooling space. What are the pain points with other tooling?

**Comment by meotimdihia** [comment]
@cheeseblubber I checked every comment service/tool last year.
The most popular free Disqus load a ton of tracking scripts.
Other tools are not really good, they are expensive and even used jQuery 
I am finding a self-hosted solution. Or if it is cheap enough.

**Comment by cheeseblubber** [comment]
@meotimdihia Wanted to follow up on this. We don't think we can get to this in the next few months since our bandwidth is a bit low. But we're working on a new api that let's you do the syncing so we can provide the data model if you'd like. We'd be happy to accept pull requests though.

Side note: I'm not sure how to make the conversation embeddable as well as google searchable besides making it a package. Iframes aren't search engine friendly. If search engine friendliness 

See more context: https://github.com/Linen-dev/linen.dev/issues/785
