### ISSUE TITLE
Read/Unread status

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#734]
Right now there is no way of tracking which threads are read and unread it makes it difficult to track which conversations is new. Similar to most chat applications they keep track of read unread.

1. When you leave Linen and come back it should track the read and unread status of your threads
    1. It should have a line of where the message is similar to most messaging apps
    2. Your scroll screen in channel view should be on the location as where you left
    3. You should have a jump to the bottom button
    4. New messages in other channels the channels tab should get highlighted
    
Technical notes:
We need to store the timestamp/cursor of when someone has left the channel. Schema wise maybe a join table between user and a channel.

**Comment by cheeseblubber** [comment]
@emilos will spike on the architecture

**Comment by emilos** [comment]
Implementation ideas:

1. Add readBy status to messages with user ids, highlight channel in the UI if any message in a channel does not have current user in read_by. `read_by` of first message is updated anytime user loads channel data. Read by on other messages is updated when user opens the thread. New messages sent through web sockets seen by the user will require a request that marks them as read. Easy to know where to scroll to in the UI for recent content. Easy to know how many messages are unread.
2. New database table with user id and message id. Keeps last viewed at date that we can compare in the UI to know if we should render the thread as read/unread. Bit more complicated because we need to do additional queries.
3. Timestamp + thread id + user id db model. We would compare last viewed at of this model vs messages. Tricky to update client side (would we send this periodically?)

Imho we could try option 1.

**Comment by emilos** [comment]
Scroll screen / last page needs remaining scroll fixes to get this done. Going to track it in the other existing story.
